\documentclass{book}


\begin{document}

<<test1>>=
## smaller font size for chunks
rm(list=ls())
setwd("C:/Users/Ben/Dropbox/Bayesian book/StanCode")
library(rstan)
library(ggplot2)
options(mc.cores=parallel::detectCores())

Y <- rnorm(10,1.5,0.2)
fit <- stan('StanJags_simpleNormal.stan',iter=200,chains=4,data=list(Y=Y))
print(fit,probs=c(0.25,0.5,0.75))
mu <- extract(fit,'mu')[[1]]

qplot(mu)

@

\end{document}